services:
  - type: web
    name: acoustic-detection-api
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: starter  # Free tier
    branch: main
    buildCommand: |
      echo "Building with Docker..."
    startCommand: |
      python run.py
    envVars:
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: PYTHONPATH
        value: /home/app
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"
